apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: allowdeletepodrb
  namespace: rbac-test1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: allowdeletepodcr
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
