apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cronjobs.batch
spec:
  group: batch
  versions:
    - name: v1beta1
      served: true
      storage: true
  names:
    plural: cronjobs
    singular: cronjob
    kind: CronJob
    shortNames:
    - cj

