apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example-cron-job
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: example-cron-job
        spec:
          containers:
          - name: example-container
            image: nginx:alpine
            command: ["echo", "Hello, World!"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

