apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment2
  template:
    metadata:
      labels:
        app: deployment2
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Hello from deployment2!'; sleep 10; done"]

