apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  template:
    metadata:
      name: example-job
    spec:
      containers:
      - name: example-container
        image: nginx:alpine
        command: ["echo", "Hello, World!"]
      restartPolicy: Never
  backoffLimit: 4
 
